services:
  billingservice:
    image: 'billingservice:latest'
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '4001:4001'
      - '9001:9001'
    networks:
      - internal

networks:
  internal:
    driver: bridge