services:
  patient-service-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin_viewer'
    ports:
      - '5432:5432'
    networks:
      - internal

  patient-service:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - patient-service-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_viewer
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    networks:
      - internal

networks:
  internal:
    driver: bridge